#cloud-config
hostname: proxy-nat
timezone: Europe/Berlin
manage_etc_hosts: true

# Enable SSH password authentication (for recovery, can be removed after initial setup)
ssh_pwauth: true

users:
  - name: admin
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups: users, admin
    shell: /bin/bash
    ssh_authorized_keys:
      - REPLACE_SSH_KEY
  - name: testuser
    gecos: Mr. Test
    groups: users
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    lock_passwd: true

# Set plain password for admin (for first login, if needed)
chpasswd:
  list: |
    admin:changeme123
  expire: false

package_update: true
package_upgrade: true
#packages:
#  - curl
#  - cloud-guest-utils
#  - e2fsprogs
#  - docker.io
#  - docker-compose
#  - iptables

#runcmd:
#  - curl -o /root/setup.sh https://raw.githubusercontent.com/danielpalaciosorantes/HomeAutomation/refs/heads/main/scripts/setup-proxy-nat.sh
#  - chmod +x /root/setup.sh
#  - /root/setup.sh

final_message: "The system is finally up, after $UPTIME seconds"