#cloud-config
hostname: proxy-nat
timezone: Europe/Berlin
manage_etc_hosts: true

users:
  - name: admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users,admin
    shell: /bin/bash

chpasswd:
  list: |
    admin:admin123
  expire: false

package_update: true
package_upgrade: true
packages:
  - curl
  - cloud-guest-utils
  - e2fsprogs
  - docker.io
  - docker-compose
  - iptables

runcmd:
  - curl -o /root/setup.sh https://github.com/danielpalaciosorantes/HomeAutomation/blob/0942c9ae7e1085fb835428b849be0663110228e7/scripts/setup-proxy-nat.sh
  - chmod +x /root/setup.sh
  - /root/setup.sh
