#cloud-config
hostname: proxy-nat
timezone: Europe/Berlin
manage_etc_hosts: true

users:
  - name: admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users,admin
    shell: /bin/bash
    lock_passwd: false
    passwd: "$6$uTGVvE1l$4qFdTz49Me0Iuj7Rlg/vIrWc.ywHJ9sWxeZAjx/YFykXrgqzDYCT/Bk1wJg7FQ3vkp3UjLtlj2qIrcPv8cGn/"

package_update: true
package_upgrade: true
packages:
  - curl
  - cloud-guest-utils
  - e2fsprogs
  - docker.io
  - docker-compose
  - iptables

runcmd:
  - curl -o /root/setup.sh https://example.com/setup-proxy-nat.sh
  - chmod +x /root/setup.sh
  - /root/setup.sh
