services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:latest
    restart: unless-stopped
    network_mode: host

    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro

    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      # or:
      # - /dev/ttyUSB0:/dev/ttyUSB0

    environment:
      TZ: Europe/Berlin
      USERNAME: ${ESPHOME_USERNAME}
      PASSWORD: ${ESPHOME_PASSWORD}